name: document-reranking-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - uvicorn=0.34.0
  - fastapi=0.115.6
  - pytest=8.0.0
  - pip:
    - torch>=2.5.1
    - flagembedding==1.3.3