name: document-reranking-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytest=8.0.0
  - pip:
    - uvicorn==0.34.0
    - fastapi==0.115.6
    - torch>=2.5.1
    - flagembedding==1.3.3
    - pydantic==2.10.3
    - httpx==0.27.0
    - transformers>=4.44.2 